query ExampleQuery($id: ID!) {
    todo(id: $id) {
        id
        title
        content
        team {
            id
            name
            avatar
        }
        status
        projectId
    }
}
